# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba5a3ad57cdc5a3cae483b3a79c9e4149c20344e5feac4bc5263569fc940b95586c21a15b1a45c743589a41738b1b3e8f69e695547ec19a7b1381c9129b06a42

test:
  secret_key_base: 5c7926044760d2e30be2d84c1fe806ff6200c39e6a7cced7b3a73eb274cf95b6de4f6497bbed81e5f4021af5fbc457650ceaf9e25fd72ce0b72e8f61fb9d6cb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
